### ISSUE TITLE
TypeError: Cannot read property 'newRating' of undefined

### ISSUE THREAD

**Issue by asalom** [LBBO/netflix-migrate#22]
Thank you for taking your time to develop this tool.

I exported the data from one account and imported it into another account which resulted in the following error. The account from where I exported the data is somewhat old, in the exported json I can see two kind of ratingType: star and thumb

export: `netflix-migrate --email email1@example.com --profile Alex --export ratings.json`
import, which caused the error: `netflix-migrate --email email2@example.com --profile Alex --import ratings.json`

```s
netflix-migrate --email email2@example.com --profile Alex --import ratings.json
Password:
/usr/local/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:225
    if (json.newRating !== rating) {
             ^

TypeError: Cannot read property 'newRating' of undefined
    at /usr/local/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:225:14
    at Request._callback (/usr/local/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:309:5)
    at Request.self.callback (/usr/local/lib/node_modules/netflix-migrate/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/netflix-migrate/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/netflix-migrate/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
```

**Comment by LBBO** [comment]
Hey Alex,

Thanks for reporting this issue! I just tried to reproduce your problem with a fresh installation and my own ratings (that also contain both star and thumb types) but everything worked just fine for me. My first guess would be that you once rated a movie that has since been deleted from Netflix or something similar.

If you don't mind and you have the time and means to do so, you could try to debug the script and give me the exact object of the rating that caused the crash. That might help me reproduce the error.

I should warn you though, that I most likely won't have much time to really look into anything this month. If this is an issue with netflix-migrate or node-netflix2, I might not be able to fix it until February or even March. Of course, you are always welcome to create a pull request yourself, if you'd like!

**Comment by asalom** [comment]
The crash happens in the `netflix2` dependency, when making some short of sanity check after the response to the netflix request
```js
this.__apiRequest(endpoint, options, function (error, response, json) {
    console.log(options)
    if (error) {
      return callback(error)
    }
    if (json.newRating !== rating) { // here crashes because json is undefined
      return callback(new Error())
    }
    callback(null)
  })
```
I tried fixing it myself but I'm unfamiliar with JavaScript. However, I did find the object causing the problem:

```json
{ rating: 2,
     authURL: 'XXX',
     titleId: 879522 },
  baseUrl: 'https://www.netflix.com/api/shakti/v68efaaa4',
  url: '/setThumbRating',
  json: true }
```

Let me know if I can help any further

**Comment by Stanzilla** [comment]
I guess I had the same issue here:

```
HttpError { name: 'HttpError', message: '401: Unauthorized' }
Error: Could not set rating for undefined. For more information, please see previous log statements.
    at /home/stan/.nvm/versions/node/v9.3.0/lib/node_modules/netflix-migrate/main.js:250:10
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by LBBO** [comment]
@Stanzilla To me, your problem seems to be unrelated to this issue, so I took the liberty of opening a new one for you. Let's continue our conversation there, unless it clearly has to do with this issue.

**Comment by bylzz** [comment]
This is due to the content has either been removed from Netflix or you are doing it from another country that hasn't got the content available. Like previously mentioned by the author above.

Just open the .json file and remove the blocks relating to the content that throws the error and run the command again, rinse & repeat.

**Comment by LBBO** [comment]
So, I just tried to reproduce this error by rating a show that is not available anymore in my country and I had no problems whatsoever. Since the issue could not be reproduced, It will be closed. Please feel free to reopen it though, if you find a way to reproduce the problem!
