### ISSUE TITLE
Migrating "My List"

### ISSUE THREAD

**Issue by N1k145** [LBBO/netflix-migrate#32]
Is it possible to migrate the watch list?

I know in the current version it is not possible, but in theory would it be possible to add this feature to the tool?

**Comment by LBBO** [comment]
Yes, it would definitely be possible. The question is: how exactly. I see one rather obvious and simple way and one rather hard way:

The simple way would be to just pretend to watch the show / the movie and trigger clicks to the video controls in order to set a specific time etc. However, this would cause a lot of traffic as parts of the video would have be loaded and netflix might have a problem with all that traffic being caused by a single IP in the short time the script would take. As a consequence, they might temporarily block the IP but I haven't tried it out yet.

The second way would be to fire API calls just like netflix does itself. I looked into that idea a few months ago and the requests that netflix sent to its servers were encrypted. I have nearly no knowledge about encryption so I have no idea how hard it would be to mimic those API calls.

There might be even more ways but these are the only ones I'm aware of.

Does this answer your question? If you'd like to, you're very welcome to research the topic a bit more! Please keep me updated if you do, though, so nobody ends up doing the same work twice.

**Comment by N1k145** [comment]
I think we are talking about different lists. I mean the one you can add movies to that you want to watch. Not the watch history

**Comment by LBBO** [comment]
Yeah, I did misunderstand you at first, but my edit refers to your actual question.

**Comment by N1k145** [comment]
Yes seen it to late, currently i also have not that much time or experience with the whole node,js stuff. But i can have a look into it

**Comment by danypacf** [comment]
https://chrome.google.com/webstore/detail/netflix-watch-list-manage/obgidigipndchfoaapdbldekffjpmmfa/related?hl=en

**Comment by LBBO** [comment]
Netflix has added official support for this feature as part of their account transfer feature, see [their official documentation](https://help.netflix.com/en/node/124844)
