### ISSUE TITLE
403

### ISSUE THREAD

**Issue by MatthewTrout** [LBBO/netflix-migrate#42]
Getting a 403 Forbidden on latest version `v0.3.6` - credentials are definitely correct!

**Comment by LBBO** [comment]
Hey Matthew,

I just tried both import and export with a fresh installation and both worked just fine. Did you check to see if you could log in via the web interface? Who knows, maybe Netflix was having an issue that has since been fixed.

Otherwise, would you mind sending me your exact command? You can leave out your personal details, if you'd like, but please let me know if they contain any special characters that might cause trouble. They shouldn't, but maybe I messed up somewhere.

**Comment by MatthewTrout** [comment]
Looks like maybe there was a Netflix issue, this morning it works! Apologies and thanks for trying yourself.
