### ISSUE TITLE
 I can't proceed

### ISSUE THREAD

**Issue by alain710** [LBBO/netflix-migrate#56]
![Screenshot 2021-02-16 at 23 44 27](https://user-images.githubusercontent.com/79153681/108078729-5e62fd00-70b1-11eb-9b7f-850994568f59.jpg)

Could not find the error details.

Well done until export. But what do you do after that? Will I have to re-import with my new profile's cookies?

**Comment by LBBO** [comment]
Hey @alain710,

thanks for reporting your issue! Turns out, I messed up while testing my latest changes. The error should be fixed in v2.0.0-beta.2 which I published just now. Please let me know if it resolves your problem or if you continue having issues!

As for how to use the import functionality: yes, if you want to upload your data to a different account, you will have to use that account's cookie (which will be different from the first cookie).

**Comment by alain710** [comment]
![Screenshot 2021-02-16 at 23 44 27](https://user-images.githubusercontent.com/79153681/108152385-4aa0b080-711c-11eb-8ce8-f3680f21193e.jpg)
Hi
Thank you for quick response. Only rationg hostory is transferred after beta 2 update. There are no viewing records, etc.
Is there any part I don't know?

**Comment by LBBO** [comment]
Yes, that is normal. As you can read in the README, viewing history import could not be implemented yet. For further information on that feature, please see #31.

I'm closing this issue as this specific problem has been resolved.
