### ISSUE TITLE
cookie-login branch returns Error: Inactive account

### ISSUE THREAD

**Issue by x0lani** [LBBO/netflix-migrate#61]
Hi, I'm not a javascript or node developer, or else I would try to help debug this.

I've copied my cookie and confirmed my login and profile are active and working, but I received an "Inactive account" error.

[errorResponsePage.zip](https://github.com/LBBO/netflix-migrate/files/6451520/errorResponsePage.zip)

Is there a more detailed log file somewhere?

`
C:\dev\netflix-migrate>node netflix-migrate --cookie "..." --profile x0lani --export netflixData.json

Using new Netflix2 class!
Logging into Netflix using Cookies

Error: Inactive account
    at Netflix.__getContextData (C:\dev\netflix-migrate\node_modules\netflix2\lib\netflix2.js:555:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Netflix.__getContextDataFromUrls (C:\dev\netflix-migrate\node_modules\netflix2\lib\netflix2.js:594:7)
    at async Netflix.login (C:\dev\netflix-migrate\node_modules\netflix2\lib\netflix2.js:76:9)
    at async main (C:\dev\netflix-migrate\netflix-migrate\main.js:24:3)

The exact response HTML file was saved to C:\dev\netflix-migrate\errorResponsePage.html

Error: There was a problem fetching user data. For more information, see previous log statements.
    at Netflix.__getContextData (C:\dev\netflix-migrate\node_modules\netflix2\lib\netflix2.js:584:13)
    at async Netflix.__getContextDataFromUrls (C:\dev\netflix-migrate\node_modules\netflix2\lib\netflix2.js:594:7)
    at async Netflix.login (C:\dev\netflix-migrate\node_modules\netflix2\lib\netflix2.js:76:9)
    at async main (C:\dev\netflix-migrate\netflix-migrate\main.js:24:3)

Error: Something went wrong. For more information, see previous log statements.
    at Netflix.login (C:\dev\netflix-migrate\node_modules\netflix2\lib\netflix2.js:88:13)
    at async main (C:\dev\netflix-migrate\netflix-migrate\main.js:24:3)
`

**Comment by jaswinder-singh** [comment]
Same issue

**Comment by Asirelith** [comment]
Same here

**Comment by cddigi** [comment]
Are you using the `memclid` cookie? I was getting the same thing. Switching to using the `NetflixId` cookie fixed that issue. Though now I'm stuck on the `HttpError: 403: Forbidden` error when it tries to set my ratings.

**Comment by Flavien06** [comment]
Hi, I had some errors too, I used another method that worked well:
1.  F12 go to "Storage", "Cookie", "netflix.com"
You can see NetflixId and SecureNetflixId
![netflix_cookie](https://user-images.githubusercontent.com/1915755/143680530-defe3c8d-d7db-43db-aa48-eaba47717fd4.png)
 2. Copy result of cookie into 2 variable : 
 `NetflixId="******"`
`SecureNetflixId="********"`
3. Use the commande
`npx netflix-migrate --cookie "NetflixId=$NetflixId;SecureNetflixId=$SecureNetflixId;" --export netflixData.json` or
`npx netflix-migrate --cookie "NetflixId=$NetflixId;SecureNetflixId=$SecureNetflixId;" --import netflixData.json`

Wouldn't it be easier to have a command like :
`npx netflix-migrate --NetflixId "*****"  --SecureNetflixId "****"`

**Comment by LBBO** [comment]
Hey everyone!

Sorry for not helping out with this issue for so long, I was just really busy and, quite frankly, fed up with playing catchup with changes to Netflix's API or DOM structure or whatever every couple of months. Your solutions look great, though they're very custom to Netflix's current cookie structure. Even if I had been active on this issue, I probably wouldn't have changed to your suggested syntax just to avoid them changing some name of a cookie property and then me having to update the project yet again.

However, there's some good news! In case anyone hasn't heard, Netflix now officially supports account migration, including viewing history! For more details, see their [official documentation](https://help.netflix.com/en/node/124844). Since that feature implements exactly what this project was aiming to do, I will officially archive this repository now (see #73). Feel free to reach out if you have any further questions!
