### ISSUE TITLE
How to run cookie-login?

### ISSUE THREAD

**Issue by vhaasteren** [LBBO/netflix-migrate#67]
I'm used to writing code, but I'm completely unfamiliar with npm/node.js. How does one run a package like this from source? I'm specifically looking at the cookie-login version, which is not published in the online npm repositories.

**Comment by sonkkeli** [comment]
What I did was that I checked out this git repo locally and installed dependencies with ‘npm i‘ and then I added the changes from this PR: https://github.com/LBBO/node-netflix2/pull/41 to the ./node_modules/node-netlix2 source code.

Also I see my comment on the PR on how I had to spy the cookie from the dev console instead of ‘document.cookie‘ which didn't work for me.

**Comment by origamiofficial** [comment]
Use this docker. It's much more simple & easy to use.
https://github.com/origamiofficial/docker-netflix-migrate/tree/main/Beta

**Comment by LBBO** [comment]
Hey everyone! Sorry for not helping out with this issue for so long, I was just really busy and, quite frankly, fed up with playing catchup with changes to Netflix's API or DOM structure or whatever every couple of months.

However, there's some good news! In case anyone hasn't heard, Netflix now officially supports account migration, including viewing history! For more details, see their [official documentation](https://help.netflix.com/en/node/124844). Since that feature implements exactly what this project was aiming to do, I will officially archive this repository now (see #73). Feel free to reach out if you have any further questions!

Also, just as an FYI: the typical workflow to work with a project like this would be the following:
1. Download Node.js / npm
2. Clone all of the repositories that you want to modify / where you want to use modified packages and run `npm install` in each repository (you can skip repos that depend on others for now)
3. If you have dependant packages that you're modifying, `cd` into them and run `npm link`. This tells npm to use this local version instead of the current published version of that package when installing other packages
4. Run `npm install` in dependant repos
5. Make your changes and run builds if necessary. The changes should be reflected in dependant repositories immediately as `npm link` just creates a few symlinks
